#pragma once

#define PLAYER_CHANNELS 2
#define PLAYER_SAMPLE_RATE 44100
#define PLAYER_SAMPLE_FORMAT paFloat32
#define PLAYER_FRAMES_PER_BUFFER 1024

#define LISTENER_CHANNELS 2
#define LISTENER_SAMPLE_RATE 44100
#define LISTENER_SAMPLE_FORMAT paFloat32
#define LISTENER_FRAMES_PER_BUFFER 1024

#define ANALYZER_FFT_WINDOW_LENGTH 1024

#define GENERATOR_SINE_WAVE_FREQUENCY 720
